spring:
  datasource:
    url: jdbc:mysql://localhost:3306/russian_post?useUnicode=true&serverTimezone=UTC
    username: russian_post_user
    password: testtest
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

server:
  port : 8090

#    Run lines below just at first database initialization

#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: russian_post.sql